In [66]:
import tensorflow as tf
print("Tensorflow version:", tf.__version__)
import numpy as np
import matplotlib.pyplot as plt
import os
import time

Tensorflow version: 2.7.0


In [67]:
#setting path
dirname = os.getcwd()
data_storerage = os.path.join(dirname, 'data\\')
print(data_storerage)

c:\Users\whylo\Desktop\MITA_Second_Year\NNDL\hw\hw2\data\


In [68]:
#load data
a = list()
b = list()
file_size = 20
filenames = ['full_numpy_bitmap_alarm clock.npy', 'full_numpy_bitmap_ant.npy', 'full_numpy_bitmap_bear.npy', 'full_numpy_bitmap_bicycle.npy', 'full_numpy_bitmap_bowtie.npy', 'full_numpy_bitmap_calculator.npy',
'full_numpy_bitmap_camel.npy', 'full_numpy_bitmap_car.npy', 'full_numpy_bitmap_cat.npy', 'full_numpy_bitmap_coffee cup.npy', 'full_numpy_bitmap_crocodile.npy', 'full_numpy_bitmap_crown.npy', 'full_numpy_bitmap_dragon.npy',
'full_numpy_bitmap_duck.npy', 'full_numpy_bitmap_elephant.npy', 'full_numpy_bitmap_eye.npy', 'full_numpy_bitmap_fan.npy', 'full_numpy_bitmap_fish.npy', 'full_numpy_bitmap_hand.npy', 'full_numpy_bitmap_house.npy']
for i in range(20):
    datasets_example=np.array(np.load(data_storerage+filenames[i]))
    temp_list = list(datasets_example)
    a = a + temp_list
    b = b+ [i]*np.shape(temp_list)[0]


In [89]:
sample = np.array(a)
label = np.array(b)


In [90]:
#shuffle 
shuffler = np.random.permutation(range(sample.shape[0]))
sample = sample[shuffler]
label = label[shuffler]


In [91]:
#setting test and train set
from keras.utils.np_utils import to_categorical
train_sample= sample[0:5000,:]
test_sample= sample[5000:7000,:]
train_label = label[0:5000]
test_label = label[5000:7000]
train_label = to_categorical(train_label) # The target variable should be categorical
test_label = to_categorical(test_label)

print(train_label[0:99])
print(test_label)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [92]:
#setting the validation set
# shuffler2= np.random.permutation(range(train_sample.shape[0]))
# train_sample = train_sample[shuffler2]
# train_label = train_label[shuffler2]
use_size = 4000
train_sample_use = train_sample[:use_size]
train_label_use = train_label[:use_size]
train_sample_sv = train_sample[use_size:]
train_label_sv = train_label[use_size:]




In [93]:
from tensorflow import  keras
from keras import models
from keras import layers

network=models.Sequential()
network.add(layers.Dense(512,activation='relu',input_shape = (28*28,)))
network.add(layers.Dense(200,activation='relu'))
network.add(layers.Dense(100,activation='relu'))
network.add(layers.Dense(50,activation='relu'))
network.add(layers.Dense(20,activation='softmax'))
opt = keras.optimizers.rmsprop(learning_rate=0.0001)
network.compile(optimizer='rmsprop',loss='categorical_crossentropy',metrics=['accuracy'])

train_sample = train_sample.reshape(np.shape(train_sample)[0],28*28)
train_sample = train_sample.astype('float32')/255
test_sample = test_sample.reshape(np.shape(test_sample)[0],28*28)
test_sample = test_sample.astype('float32')/255

##network.fit(train_sample, train_label, epochs=20, batch_size=128)

#early stop
early_stopping = keras.callbacks.EarlyStopping(patience=10,restore_best_weights=True)
history=network.fit(train_sample_use, train_label_use, 
                    validation_data=(train_sample_sv,train_label_sv),
                    epochs=300, batch_size=128,
                    callbacks=[early_stopping]
                    )
test_loss, test_acc=network.evaluate(test_sample, test_label) #Apply the learned network to the test data
print('test_acc:',test_acc) 


AttributeError: module 'keras.api._v2.keras.optimizers' has no attribute 'rmsprop'