In [1]:
import tensorflow as tf
print("Tensorflow version:", tf.__version__)
import numpy as np
import matplotlib.pyplot as plt
import os

Tensorflow version: 2.7.0


In [6]:
#setting path
dirname = os.getcwd()
dataStorerage = os.path.join(dirname, 'data\\')
print(dataStorerage)

c:\Users\whylo\Desktop\MITA_Second_Year\NNDL\hw\hw2\data\


In [22]:
#load data
fileNames = ['full_numpy_bitmap_alarm clock.npy', 'full_numpy_bitmap_ant.npy', 'full_numpy_bitmap_bear.npy', 'full_numpy_bitmap_bicycle.npy', 'full_numpy_bitmap_bowtie.npy', 'full_numpy_bitmap_calculator.npy',
'full_numpy_bitmap_camel.npy', 'full_numpy_bitmap_car.npy', 'full_numpy_bitmap_cat.npy', 'full_numpy_bitmap_coffee cup.npy', 'full_numpy_bitmap_crocodile.npy', 'full_numpy_bitmap_crown.npy', 'full_numpy_bitmap_dragon.npy',
'full_numpy_bitmap_duck.npy', 'full_numpy_bitmap_elephant.npy', 'full_numpy_bitmap_eye.npy', 'full_numpy_bitmap_fan.npy', 'full_numpy_bitmap_fish.npy', 'full_numpy_bitmap_hand.npy', 'full_numpy_bitmap_house.npy']

dataSets_example=np.array([np.load(dataStorerage+fileName,encoding='ASCII') for fileName in fileNames],dtype=object)
dataSets_label = np.array([[i]for inArray in dataSets_example[i]])

dataSets

array([array([[0, 0, 0, ..., 0, 0, 0],
              [0, 0, 0, ..., 0, 0, 0],
              [0, 0, 0, ..., 0, 0, 0],
              ...,
              [0, 0, 0, ..., 0, 0, 0],
              [0, 0, 0, ..., 0, 0, 0],
              [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
       array([[0, 0, 0, ..., 0, 0, 0],
              [0, 0, 0, ..., 0, 0, 0],
              [0, 0, 0, ..., 0, 0, 0],
              ...,
              [0, 0, 0, ..., 0, 0, 0],
              [0, 0, 0, ..., 0, 0, 0],
              [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
       array([[0, 0, 0, ..., 0, 0, 0],
              [0, 0, 0, ..., 0, 0, 0],
              [0, 0, 0, ..., 0, 0, 0],
              ...,
              [0, 0, 0, ..., 0, 0, 0],
              [0, 0, 0, ..., 0, 0, 0],
              [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
       array([[0, 0, 0, ..., 0, 0, 0],
              [0, 0, 0, ..., 0, 0, 0],
              [0, 0, 0, ..., 0, 0, 0],
              ...,
              [0, 0, 0, ..., 0, 0, 0],
              [0, 0, 

SyntaxError: invalid syntax (Temp/ipykernel_13636/939532428.py, line 4)